branch-defaults:
  default:
    environment: csudemo3
  master:
    environment: csudemo3
environment-defaults:
  csusm:
    branch: null
    repository: null
global:
  application_name: scholarworks
  default_ec2_keyname: aws-prod-oregon
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Puma with Ruby 2.3
    running on 64bit Amazon Linux/2.3.3
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
