terms:
  - term: "College of Extended and International Education"
  - term: "College of Natural and Behavioral Sciences"
  - term: "College of Education"
  - term: "College of Arts and Humanities"
  - term: "College of Health, Human Services, and Nursing"
