terms:
  - term: "Academic Senate"
  - term: "Administration"
  - term: "Arboretum"
  - term: "Associated Students"
  - term: "Auxiliary Services Corporation"
  - term: "College of the Arts"
  - term: "College of Communications"
  - term: "College of Education"
  - term: "College of Engineering and Computer Science"
  - term: "College of Health and Human Development"
  - term: "College of Humanities and Social Sciences"
  - term: "College of Natural Sciences and Mathematics"
  - term: "Honors Program"
  - term: "Mihaylo College of Business and Economics"
  - term: "Pollak Library"
