terms:
  - term: "Mike Curb College of Arts, Media, and Communication"
  - term: "David Nazarian College of Business and Economics"
  - term: "Michael D. Eisner College of Education"
  - term: "College of Engineering and Computer Science"
  - term: "College of Health and Human Development"
  - term: "College of Humanities"
  - term: "Delmar T Oviatt Library"
  - term: "College of Science and Mathematics"
  - term: "College of Social and Behavioral Sciences"
  - term: "The Tseng College"
