terms:
 - term: "Anthropology"
 - term: "Art"
 - term: "Biology"
 - term: "Business"
 - term: "Chemistry"
 - term: "Child Development"
 - term: "Communication"
 - term: "Computer Science"
 - term: "Critical Race, Gender, and Sexuality Studies"
 - term: "Dance"
 - term: "Economics"
 - term: "Education"
 - term: "English"
 - term: "Environment & Community"
 - term: "Environmental Resources Engineering"
 - term: "Environmental Science & Management"
 - term: "Environmental Studies"
 - term: "Environmental Systems"
 - term: "Film"
 - term: "Fisheries"
 - term: "Forestry"
 - term: "Geography"
 - term: "Geology"
 - term: "Globalization"
 - term: "History"
 - term: "International Studies"
 - term: "Journalism & Mass Communications"
 - term: "Kinesiology"
 - term: "Leadership Studies"
 - term: "Mathematics"
 - term: "Music"
 - term: "Native American Studies"
 - term: "Natural Resources"
 - term: "Oceanography"
 - term: "Philosophy"
 - term: "Physical Education"
 - term: "Physics"
 - term: "Political Science"
 - term: "Psychology"
 - term: "Religious Studies"
 - term: "Social Science"
 - term: "Social Work"
 - term: "Sociology"
 - term: "Theatre Arts"
 - term: "Wildlife"
 - term: "World Languages & Cultures"
