terms:
  - term: "Accounting and Finance"
  - term: "Advanced Educational Studies"
  - term: "Anthropology"
  - term: "Art"
  - term: "Biology"
  - term: "Chemistry and Biochemistry"
  - term: "Child, Adolescent, and Family Studies"
  - term: "Communications"
  - term: "Computer and Electrical Engineering and Computer Science"
  - term: "Criminal Justice"
  - term: "Economics"
  - term: "Educational Leadership (DEPL)"
  - term: "English"
  - term: "Geological Sciences"
  - term: "History"
  - term: "Interdisciplinary Studies"
  - term: "Kinesiology"
  - term: "Liberal Studies"
  - term: "Management and Marketing"
  - term: "Mathematics"
  - term: "Modern Languages and Literatures"
  - term: "Music"
  - term: "Nursing"
  - term: "Philosophy and Religious Studies"
  - term: "Physics and Engineering"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Public Policy and Administration"
  - term: "Social Work"
  - term: "Sociology"
  - term: "Teacher Education"
  - term: "Theatre"
