terms:
  - term: "Anthropology"
  - term: "Biology"
  - term: "Business Administration"
  - term: "Computer and Engineering Science"
  - term: "Counseling"
  - term: "Education"
  - term: "English"
  - term: "Film Studies"
  - term: "History"
  - term: "Hutchins School of Liberal Studies"
  - term: "Interdisciplinary Studies Program"
  - term: "Kinesiology"
  - term: "Modern Languages"
  - term: "Nursing"
  - term: "Organization Development"
  - term: "Political Science"
  - term: "Psychology"
