terms:
  - term: "Humanities External Program"
  - term: "Quality Assurance Program"
  - term: "Department of Biology"
  - term: "Department of Computer Science"
  - term: "Department of Sociology"
  - term: "Department of Psychology"
  - term: "Division of Graduate Education"
  - term: "Department of English"
  - term: "Department of History"
  - term: "Department of Interdisciplinary Studies"
  - term: "Department of Philosophy"
  - term: "Department of Social Work"
