terms:
  - term: "Accountancy"
  - term: "Anthropology"
  - term: "Art"
  - term: "Asian American Studies"
  - term: "Biology"
  - term: "Broadcast and Electronic Communication Arts"
  - term: "Business Administration"
  - term: "Business Analytics"
  - term: "Chemistry and Biochemistry"
  - term: "Chinese"
  - term: "Cinema Studies"
  - term: "Classics"
  - term: "Clinical Mental Health Counseling"
  - term: "Communication Studies"
  - term: "Communicative Disorders"
  - term: "Comparative and World Literature"
  - term: "Computer Science"
  - term: "Counseling"
  - term: "Design"
  - term: "Economics"
  - term: "Education"
  - term: "Education: Concentration in Special Education"
  - term: "Educational Leadership"
  - term: "Engineering"
  - term: "English"
  - term: "English: Creative Writing"
  - term: "English: Teaching English to Speakers of Other Languages"
  - term: "Ethnic Studies"
  - term: "Family & Consumer Sciences"
  - term: "French"
  - term: "Geographic Information Science"
  - term: "Geography"
  - term: "Geosciences"
  - term: "German"
  - term: "Gerontology"
  - term: "History"
  - term: "Human Sexuality Studies"
  - term: "Humanities"
  - term: "Interdisciplinary Marine and Estuary Sciences"
  - term: "International Relations"
  - term: "Italian"
  - term: "Japanese"
  - term: "Kinesiology"
  - term: "Mathematics"
  - term: "Museum Studies"
  - term: "Music"
  - term: "Nursing"
  - term: "Philosophy"
  - term: "Physical Therapy"
  - term: "Physics"
  - term: "Political Science"
  - term: "Psychology"
  - term: "Public Administration"
  - term: "Public Health"
  - term: "Recreation, Parks & Tourism"
  - term: "Social Work"
  - term: "Spanish"
  - term: "Special Education"
  - term: "Theatre Arts"
  - term: "Women and Gender Studies"
