terms:
    - id: http://creativecommons.org/licenses/by/3.0/us/
      term: Attribution 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-sa/3.0/us/
      term: Attribution-ShareAlike 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nc/3.0/us/
      term: Attribution-NonCommercial 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nd/3.0/us/
      term: Attribution-NoDerivs 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nc-nd/3.0/us/
      term: Attribution-NonCommercial-NoDerivs 3.0 United States
      active: true
    - id: http://creativecommons.org/licenses/by-nc-sa/3.0/us/
      term: Attribution-NonCommercial-ShareAlike 3.0 United States
      active: true
    - id: http://creativecommons.org/publicdomain/zero/1.0/
      term: CC0 1.0 Universal
      active: true
    - id: http://www.europeana.eu/portal/rights/rr-r.html
      term: All rights reserved
      active: true
    - id: http://opendatacommons.org/licenses/odbl/1.0/
      term: Open Data Commons Open Database License (ODbL)
      active: true
    - id:  http://www.opendatacommons.org/licenses/pddl/1.0/
      term: Open Data Commons Public Domain Dedication and License (PDDL)
      active: true
    - id: https://opendatacommons.org/licenses/by/1.0/
      term: Open Data Commons Attribution License (ODC-By) v1.0
      active: true
