terms:
  - id: Animation
    term: Animation
  - id: Assessment Tool
    term: Assessment Tool
  - id: Assignment
    term: Assignment
  - id: Case Study
    term: Case Study
  - id: Collection
    term: Collection
  - id: Development Tool
    term: Development Tool
  - id: Drill and Practice
    term: Drill and Practice
  - id: ePortfolio
    term: ePortfolio
  - id: Hybrid/Blended Course
    term: Hybrid/Blended Course
  - id: Illustration/Graphic
    term: Illustration/Graphic
  - id: Learning Object Repository
    term: Learning Object Repository
  - id: Online Course
    term: Online Course
  - id: Online Course Module
    term: Online Course Module
  - id: Open Textbook
    term: Open Textbook
  - id: Photographic Image - Instructional
    term: Photographic Image
  - id: Presentation
    term: Presentation
  - id: Quiz/Test
    term: Quiz/Test
  - id: Reference Material
    term: Reference Material
  - id: Simulation
    term: Simulation
  - id: Social Networking Tool
    term: Social Networking Tool
  - id: Syllabus
    term: Syllabus
  - id: Tutorial
    term: Tutorial
  - id: Workshop and Training Material
    term: Workshop and Training Material
  - id: Video - Instructional
    term: Video - Instructional
  - id: Other
    term: Other
